### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by anupm12**
Decent looking.

### CODE REVIEW

**Comment by anupm12** [comment]
Hello,
Here is the direct link:
https://codepen.io/anupm12/pen/bOOJYw

**Comment by aswinzz** [comment]
@LGTM 👍

**Comment by anupm12** [comment]
@zerefwayne please review this PR.

**Comment by anupm12** [comment]
@pradeepgangwar Please review this PR.
Waiting for the past 3 days.

**Comment by pradeepgangwar** [comment]
LGTM @zerefwayne Please review the PR and let him know changes if any.

**Pull request merged**
