### PR TITLE
#35- Artwork 3(Cat)

### PR DESCRIPTION
**Pull request by Archies11**
Codepen Link: https://codepen.io/archies11/pen/NeQbxV

### CODE REVIEW

**Comment by aswinzz** [comment]
LGTM 👍

**Comment by Jigar3** [comment]
@Archies11  Good work. Just resolve the conflicts.

**Comment by Archies11** [comment]
Resolved the comflicts.

**Comment by Jigar3** [comment]
@Archies11 in artworks.md, you have added same links for flower and cat. Change it and submit a PR

**Pull request merged**
